services:
  kasmweb-ubuntu-focal-desktop:
    image: "kasmweb-ubuntu-focal-desktop:root"
    privileged: true
    build: ./ubuntu
    shm_size: "2gb"
    ports:
      - "4901:4901"
      - "5901:5901"
      - "6901:6901"
    volumes:
    - ./ubuntu/kasm-user/:/home/kasm-user/:rw
    cap_add:
      - SYS_ADMIN
    environment:
      VNC_PW: 'password'
      AUDIO_PORT: 4901
      LANG: "es_ES.UTF-8"
      LANGUAGE: "es_ES:es"
      LC_ALL: "es_ES.UTF-8"
      SHELL: "/bin/bash"
      TZ: "CET"
    networks:
      - proxynet
      
  kasmweb-nginx:
    image: "nginx"
    ports:
      - "443:443"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/ssl/:/etc/nginx/ssl/
    - ./nginx/users/:/etc/nginx/users/
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
    external: true
# sudo docker-compose up -d
# sudo docker-compose build
